version: "3"

services:
  proxy:
    image: traefik
    restart: unless-stopped
    networks:
      - web
    environment:
      LETS_ENCRYPT_EMAIL: ${LETS_ENCRYPT_EMAIL}
      BASIC_AUTH: ${BASIC_AUTH}
      DASHBOARD_FRONTEND: ${DASHBOARD_FRONTEND}
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
      - ./volumes/acme:/acme # Tell Traefik to save SSL certs here
      - ./volumes/certs:/certs
    command:
      - "--api"
      - "--defaultEntryPoints=http,https"
      - "--debug=true"
      - "--entrypoints=Name:http address::80 redirect.entryPoint:https"
      - "--entryPoints=Name:https address::443 TLS:/certs/wildcard_loc.crt,/certs/wildcard_loc.key"
      - "--acme"
      - "--acme.entryPoint=https"
      - "--acme.storage=/acme/acme.json"
      - "--acme.email=${LETS_ENCRYPT_EMAIL}"
      - "--acme.acmeLogging=true"
      - "--acme.onHostRule=true"
      - "--acme.httpChallenge.entryPoint=http"
      - "--docker"
      - "--docker.watch=true"
      - "--docker.exposedByDefault=false"
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:$DASHBOARD_FRONTEND"
      - "traefik.frontend.auth.basic=$BASIC_AUTH"
      - "traefik.port=8080"

networks:
  web:
    external: true
