version: "3"

networks:
  web:
    external: true

services:
  proxy:
    image: traefik
    restart: unless-stopped
    networks:
      - web
    environment:
      LETS_ENCRYPT_EMAIL: ${LETS_ENCRYPT_EMAIL}
      DASHBOARD_BASIC_AUTH: ${DASHBOARD_BASIC_AUTH}
      DASHBOARD_FRONTEND: ${DASHBOARD_FRONTEND}
    ports:
      - "80:80"
      - "443:443"
      # - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/acme:/acme
      - ./volumes/certs:/certs
    command:
      - "--api"
      - "--defaultEntryPoints=http,https"
      - "--debug=true"
      - "--entrypoints=Name:http address::80 redirect.entryPoint:https Compress:true"
      - "--entryPoints=Name:https address::443 TLS:/certs/wildcard_loc.crt,/certs/wildcard_loc.key Compress:true"
      - "--acme"
      - "--acme.email=${LETS_ENCRYPT_EMAIL}"
      - "--acme.storage=/acme/acme.json"
      - "--acme.entryPoint=https"
      - "--acme.dnsChallenge=true"
      - "--acme.dnschallenge.provider=cloudflare"
      - "--acme.acmeLogging=true"
      - "--docker"
      - "--docker.watch=true"
      - "--docker.exposedByDefault=false"
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:$DASHBOARD_FRONTEND"
      - "traefik.frontend.auth.basic=$DASHBOARD_BASIC_AUTH"
      - "traefik.port=8080"
    environment:
      - CLOUDFLARE_EMAIL: ${CLOUDFLARE_EMAIL}
      - CLOUDFLARE_API_KEY: ${CLOUDFLARE_API_KEY}
